replicaCount: 1

nameOverride: ""
fullnameOverride: ""

image:
  repository: k8s-remote-debugger
  tag: local
  pullPolicy: Never

debug:
  enabled: true
  port: 5678
  waitForClient: false

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

probes:
  readiness:
    path: /healthz
    initialDelaySeconds: 2
    periodSeconds: 5
  liveness:
    path: /healthz
    initialDelaySeconds: 5
    periodSeconds: 10
